name: Sync Submodules Commits

on:
  workflow_dispatch:
  # 定时任务，每天在 UTC 时间 00:00 执行
  schedule:
    - cron:  '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          # 确保将 submodules 也检出
          submodules: 'recursive'

      # 同步子模块的 commit 信息
      - name: Sync submodule commits
        run: |
          git submodule update --recursive --remote
      # 如果submodule有更新，则提交到主仓库
      - name: Commit changes
        run: |
          git config --global user.name 'lvjing2'
          git config --global user.email 'leojames.googol@gmail.com'
          git add .
          git commit -m "Updated submodules to latest commits" || echo "No commits to update"
          git push

# 注意：该工作流程只是一个模板，具体详细逻辑可能需要在脚本中实现，并且需要适当配置您的Git 用户名和邮箱。
